on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install moreutils
        run: sudo apt-get install -y moreutils
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create chrome & firefox release bundles
        run: |
          ./scripts/create-bundle.sh chrome
          ./scripts/create-bundle.sh firefox
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "chinese-dict-chrome.zip,chinese-dict-firefox.zip"
